<?php
// This file does the initial database installation for the Havyaka Culture project
include_once 'includes/constants/sql_constants.php';
//include_once 'includes/constants/dbc.php';

// Creates our SQL from a file generated by MySQL Workbench. This file is updated when we modify our database tables or structure.
$install_sql = file_get_contents('create_scripts.sql');

?>

<form method="get" action="<?php echo BASE;?>/install.php" name="install">
	<p>Install or reset the database:<br>
	<input type="submit" class="submit" name="cmd" value="install" /></p>
</form>

<form method="get" action="<?php echo BASE;?>/install.php" name="dummy_data">
	<p>Populate the database with dummy data:<br>
	<input type="submit" class="submit" name="cmd" value="dummy_data" /></p>
</form>

<?php
// Check for get data
if($_GET){
	/* installs or resets the database to an empty state */
	if ($_GET['cmd'] == 'install'){
		$select = mysqli_select_db($link, DB_NAME);

		$install = mysqli_multi_query($link, $install_sql);
		if($install){
			echo "<p>Database installed successfully<p>";
		}
		else{
			echo "<p>Database install failed.<p>";
		}
	}
	
	/* Adds dummy data to our database for testing purposes. */
	if ($_GET['cmd'] == 'dummy_data'){
		$table = array(LOCATION, COMMUNITY_TYPE, USERS, CHEF, EVENT_TYPE, FOOD, VENUE, EVENT_RECURRENCE, EVENT, FOOD_CHEF_DETAILS, USER_SAVED_INFO, ATTENDANCE, EVENT_PICTURE);
		
		$select = mysqli_select_db($link, DB_NAME);
		
		$q_insert_pstore = mysqli_query($link,"INSERT INTO ".PSTORE. " (p_id,p_email,p_pass) VALUES(1,AES_ENCRYPT('connect.community.culture@gmail.com','ae4bca65f3283fe26a6d3b10b85c3a308'),AES_ENCRYPT('connectcommunity1','ae4bca65f3283fe26a6d3b10b85c3a308')");
		
		for ($i = 0; $i < count($table); $i++){
			$name = $table[$i];
			/* 
			SQL to load data from our CSV files. Example:
			LOAD DATA INFILE 'C:/wamp/www/havyaka_culture/dummy_data/user.txt'
			INTO TABLE user 
			*/
			
			/* $dummy_sql = "LOAD DATA INFILE '" . ROOT . "/dummy_data/$name.txt'
			INTO TABLE $name"; */
 			$dummy_sql = "LOAD DATA INFILE '" . ROOT . "/dummy_data/$name.csv'
			INTO TABLE $name
			FIELDS TERMINATED BY ','
			OPTIONALLY ENCLOSED BY '\"' 
			LINES TERMINATED BY '\n';";
			
			$install = mysqli_query($link, $dummy_sql) /* or die(mysql_error()) */;
                        if($install && $q_insert_pstore){
			    echo "<p>Dummy data inserted into " . $table[$i] . " successfully<p>";
			}
			else{
                            echo "<p>" . $dummy_sql . "</p>";
                            echo "<p>Dummy data install failed.<p>";
			}
			
		}
	}
}

?>