<?php
// This file does the initial database installation for the Havyaka Culture project
include_once 'includes/constants/sql_constants.php';
include_once 'includes/constants/dbc.php';

// Creates our SQL from a file generated by MySQL Workbench. This file is updated when we modify our database tables or structure.
$install_sql = file_get_contents('create_scripts.sql');

?>

<form method="get" action="<?php echo BASE;?>/install.php" name="install">
	<p>Install or reset the database:<br>
	<input type="submit" class="submit" name="cmd" value="install" /></p>
</form>

<form method="get" action="<?php echo BASE;?>/install.php" name="dummy_data">
	<p>Populate the database with dummy data:<br>
	<input type="submit" class="submit" name="cmd" value="dummy_data" /></p>
</form>

<?php
// Check for get data
if($_GET){
	/* installs or resets the database to an empty state */
	if ($_GET['cmd'] == 'install'){
		$select = mysqli_select_db($link, DB_NAME);

		$install = mysqli_multi_query($link, $install_sql);
		if($install){
			echo "<p>Database installed successfully<p>";
		}
		else{
			echo "<p>Database install failed.<p>";
		}
	}
	
	/* Adds dummy data to our database for testing purposes. */
	if ($_GET['cmd'] == 'dummy_data'){
		$table = array("location", "community", "user", "chef", "event_type", "food", "venue", "event_recurrence","event", "food_chef_details", "user_saved_info", "event_attendance"/*, "event_picture"*/);
		
		$select = mysqli_select_db($link, DB_NAME);
		
		for ($i = 0; $i < count($table); $i++){
			$name = $table[$i];
			/* 
			SQL to load data from our CSV files. Example:
			LOAD DATA INFILE 'C:/wamp/www/havyaka_culture/dummy_data/user.txt'
			INTO TABLE user 
			*/
			
			$dummy_sql = "LOAD DATA INFILE 'C:/wamp/www/havyaka_culture/dummy_data/$name.txt'
			INTO TABLE $name;";
						
			$install = mysqli_query($link, $dummy_sql) or die(mysql_error());
			if($install){
				echo "<p>Dummy data inserted into " . $table[$i] . " successfully<p>";
			}
			else{
				echo "<p>" . $dummy_sql "</p>";
				echo "<p>Dummy data install failed.<p>";
			}
			
		}
	}
}

?>